### ISSUE TITLE
about video inference

### ISSUE THREAD

**Issue by QiqLiang** [huawei-noah/Efficient-Computing#100]
你好，我想用训练好的模型在自己本地的.mp4视频文件上做推理，推理可视化结果保存为.mp4文件，请问我要怎么修改代码呢？谢谢！

**Comment by Egorundel** [comment]
我认为你应该翻译训练后获得的权重weights.pt 到ONNX模型，然后将其转换到TensorRT引擎。 然后在网上找到或者自己写一个c++中的推理代码，将使用TensorRT引擎。
