### ISSUE TITLE
配置文件中的use_dfl与reg_max什么含义，为什么readme文件中不使用蒸馏学习时依旧要求设置use_dfl为True

### ISSUE THREAD

**Issue by Unicorn123455678** [huawei-noah/Efficient-Computing#101]

**Comment by lose4578** [comment]
Please refer this https://github.com/huawei-noah/Efficient-Computing/issues/68#issuecomment-1734711096 .

**Comment by lose4578** [comment]
If you don't use self-distill, you can set `use_dfl=False`. use_dfl is a method to improve the teacher model performance.

**Comment by QiqLiang** [comment]
意思是假如之后要把这个模型作为教师模型的话，训练教师模型也要把use_dfl设置为True吗？

**Comment by lose4578** [comment]
> 意思是假如之后要把这个模型作为教师模型的话，训练教师模型也要把use_dfl设置为True吗？

Yes
