### ISSUE TITLE
 ERROR in training steps: Default process group has not been initialized, please make sure to call init_process_group.

### ISSUE THREAD

**Issue by KaTelllyyy** [huawei-noah/Efficient-Computing#102]
您好，我在单机单卡上训练gold-yolo遇见了这样的报错，请问我该如何解决这个问题？
ERROR in training steps: Default process group has not been initialized, please make sure to call init_process_group.

**Comment by lose4578** [comment]
Please refer this https://github.com/huawei-noah/Efficient-Computing/issues/68#issuecomment-1734711096 .

**Comment by KaTelllyyy** [comment]
谢谢您的回答，当我安装您的建议修改后，在训练80多轮（一共100轮）时出现了以下报错，请问我该如何解决这个问题？
OSError: [WinError 1455] 页面文件太小，无法完成操作。 Error loading "E:\Anconda3.2021.05.64.py3.8\envs\detection\lib\site-packages\torch\lib\cudnn_adv_infer64_8.dll" or one of its dependencies.

**Comment by lose4578** [comment]
You can check your memory usage.

**Comment by KaTelllyyy** [comment]
感谢您关于以上的回复！此外，我在推理时仍然遇到了麻烦。具体地说，我训练好了一个Gold-YOLO模型权重文件（last_ckpt.pt），并调整好了推理所需的参数设置，但是仍然出现以下这样的报错，请问我该如何解决这种问题？
TypeError: __init__() missing 2 required positional arguments: 'img_size' and 'half'
![image](https://github.com/huawei-noah/Efficient-Computing/assets/126141736/caeb129f-75cd-41b3-9988-4b7a0f436690)

**Comment by lose4578** [comment]
If you running code is infer.py, maybe you can update the related code from YOLOv6.
We didn't verify that infer.py is available.
