### ISSUE TITLE
[Gold-Yolo]inject module

### ISSUE THREAD

**Issue by lkikinn** [huawei-noah/Efficient-Computing#105]
Why is the Inject Module divided into two parts?

**Comment by lose4578** [comment]
Different branches are used to deal with different sizes of targets, and are also the results of precision-speed weighing.

**Comment by lose4578** [comment]
This is the result of the precision-speed trade-off.

**Comment by lkikinn** [comment]
I understand that some people say that the act part can be seen as attention weight, and the whole can be seen as a process of a simple attention mechanism, like a * w + b.I don't know if that's right。

**Comment by lose4578** [comment]
Yes, the implementation of inject is a variant of attention, and of course the specific operators used to implement inject can be changed according to the actual situation, without being limited to the attention structure
