### ISSUE TITLE
infer.py精度与eval.py精度差距过大

### ISSUE THREAD

**Issue by kaka-Cao** [huawei-noah/Efficient-Computing#107]
我使用自己的数据集训练gold-yolo_n后，在eval.py上测试的map50精度为（遵循默认设置）90，而在infer.py上使用相同的权重并遵循默认设置，将推理结果的txt文件与groundtruth标签进行了对比，计算得到的map50为34，这是为什么，我应该调整什么参数吗。我的数据集分辨率从800到1500，我将他们训练时全部resize到了800进行训练，在验证时image_size为800，test_load_size为636，推理时image_size为636.

**Comment by diplomatist** [comment]
可能eval开启了--reproduce_640_eval，而infer没开启，这个参数会执行包含了letterbox的操作，你可以测试下宽高比为1的图片测试下eval和infer的区别

**Comment by kewang-seu** [comment]
您好，请问这个问题解决了吗？我用COCO预训练模型在eval和infer时，精度也出现了很大差异，推理的结果非常差，几乎检测不到目标，但从eval的精度来看，还是可以的。这是为什么呢？
