### ISSUE TITLE
Can't make inferences

### ISSUE THREAD

**Issue by leonokida** [huawei-noah/Efficient-Computing#108]
Hello, I'm having some trouble running the inference task:
`TypeError: Inferer.__init__() missing 2 required positional arguments: 'img_size' and 'half'`
I am running the command:
`python tools/infer.py --weights $1 --source dataset/images/test --img-size 640python tools/infer.py --weights $1 --source dataset/images/test --img-size 640`
where `$1` is the name of the `.pt` file.  
What am I doing wrong? Thanks in advance!

**Comment by lose4578** [comment]
Sorry, we didn't verify that infer.py is available, maybe you can find the latest code from YOLOv6.

**Comment by leonokida** [comment]
Sorry I took so long to respond, but I was able to make it work using the following command before running the `infer.py` script:
`sed -i "s/inferer = Inferer(source, weights, device, yaml, img_size, half)/inferer = Inferer(source, False, None, weights, device, yaml, img_size, half)/g" ./tools/infer.py`
