### ISSUE TITLE
about video inference

### ISSUE THREAD

**Issue by QiqLiang** [huawei-noah/Efficient-Computing#109]
你好，我在自己的数据集微调后，在验证集上各项指标如mAP值都有所提升，但是在视频进行检测会发现很多背景被误报为前景目标，而yolov6就不会有类似的误报，这是为什么呢？请问有什么解决方法？谢谢！

**Comment by lose4578** [comment]
Perhaps you can adjust the inference parameters, like `--conf-thres`
