### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Egorundel** [huawei-noah/Efficient-Computing#110]
Hello, I was training the network, but at some point I ran out of memory on the device. I freed up memory and wanted to run the --resume command, but I got an error: `TypeError: 'NoneType' object is not subscriptable`

![Screenshot from 2023-11-03 09-19-44](https://github.com/huawei-noah/Efficient-Computing/assets/65890558/dd3f39f2-6975-4f1f-bb44-83b878c0814f)

Can you tell me what needs to be done to fix it and continue training?

**Comment by lose4578** [comment]
Perhaps you can look at your folder and check that the ckpt is complete.

**Comment by AnShuai666** [comment]
The same error to resume traing, have you resolved this problem, many thanks!

**Comment by AnShuai666** [comment]
The same error to resume training, have you resolved this problem? Many thanks!

**Comment by Tuerte** [comment]
I had the same problem. Did you solve it?
