### ISSUE TITLE
Add the Gold-yolo module to yolov7

### ISSUE THREAD

**Issue by xlnn** [huawei-noah/Efficient-Computing#112]
Thank you for your excellent work, may I ask how to add the Gold-yolo module to yolov7? Thanks!

**Comment by lose4578** [comment]
The specific implementation of GD Neck can be found in `gold_yolo/reppan.py`, and the exact number of channels and other details can be adjusted. If you migrate successfully, you are welcome to open source it.

**Comment by lose4578** [comment]
t
