### ISSUE TITLE
missing labels and low evaluation

### ISSUE THREAD

**Issue by Egorundel** [huawei-noah/Efficient-Computing#113]
Hello, can you tell me, I want to do validation, but for some reason I have low accuracy rates. And it's also as if validation is not checked on the entire dataset. Why are only 246 labels found and 2366 are missing?

About labels:
![2023_11_16_0lh_Kleki](https://github.com/huawei-noah/Efficient-Computing/assets/65890558/59204724-5c75-4c96-9ec2-38b05b0744c2)

About low accuracy rates:
![Screenshot from 2023-11-16 12-57-38](https://github.com/huawei-noah/Efficient-Computing/assets/65890558/c48a6d1c-3e3b-4dfe-8fbe-4f98539720ef)

**Comment by lose4578** [comment]
During training, the code automatically checks the accuracy of the training data, and the problematic data is skipped. Perhaps you can check that your training data is correct and complete.

**Comment by Egorundel** [comment]
@lose4578 And what data can be considered problematic?

**Comment by lose4578** [comment]
You can refer this https://github.com/huawei-noah/Efficient-Computing/blob/master/Detection/Gold-YOLO/yolov6/data/datasets.py#L493 and this https://github.com/huawei-noah/Efficient-Computing/blob/master/Detection/Gold-YOLO/yolov6/data/datasets.py#L493
