### ISSUE TITLE
Feature map size Question?

### ISSUE THREAD

**Issue by Rosal-1998** [huawei-noah/Efficient-Computing#118]
您好，最近在看您的论文，在High-FAM中P5,P4,P3输入进去，但在代码里面为什么P5也进行了池化？难道不是只有P4,P3池化调整到【20，20】吗？您的代码里面他们都调整到了【10，10】。请问为什么？

**Comment by lose4578** [comment]
This is faster and has less impact on accuracy

**Comment by Rosal-1998** [comment]
> This is faster and has less impact on accuracy

thank you!
