### ISSUE TITLE
The script of generating text for GPT4Image

### ISSUE THREAD

**Issue by Chzzi** [huawei-noah/Efficient-Computing#119]
I'm trying to transfer GPT4Image from ImageNet to a custom dataset. How can I generate the corresponding text for the batch of images through MiniGPT4? Could you please provide a reference script?

**Comment by dingning97** [comment]
I used a very old version of MiniGPT4, and  the last commit might be "commit-22d8888" on May 1, 2023. You might access those lagacy codes throught this link: https://github.com/Vision-CAIR/MiniGPT-4/tree/22d8888ca2cf0aac862f537e7d22ef5830036808
