### ISSUE TITLE
hyper-parameter "--fuse_ab" in gold-yolo

### ISSUE THREAD

**Issue by QiqLiang** [huawei-noah/Efficient-Computing#120]
Hi, i want to know if fuse_ab=True means that we use anchors-based branch as auxiliary when training while we throw it away when infering? Cuz i print the model structure while infering and find that there is still a cls_preds_ab branch and a reg_preds_ab branch printed. Is it more reasonable that there is only cls_preds_af branch and reg_preds_af branch？Why does it happen and how can i solve it?

**Comment by lose4578** [comment]
https://github.com/meituan/YOLOv6/issues/968
