### ISSUE TITLE
gold_yolo训练自己的数据集失败

### ISSUE THREAD

**Issue by yaosx425** [huawei-noah/Efficient-Computing#130]
![single_axis_0005](https://github.com/huawei-noah/Efficient-Computing/assets/142800903/4cf263bc-4721-42aa-bb71-f64d0297fa57)
测试结果如图，我按照您说的labels格式进行了训练，但是测试结果 为什么标的框整体都在上面呢 测试了好多张图片 标注的框都紧贴着图片最上边 不知道您有没有遇到过这种问题 这是什么原因呢

**Comment by yaosx425** [comment]
![Uploading single_axis_0005.jpg…]()

**Comment by lose4578** [comment]
Maybe you have some problem in label convert, like the xyxy to xyhw, or the coordinate scale is not set correct.
