### ISSUE TITLE
Does the model support OBB detection?

### ISSUE THREAD

**Issue by 13253318778** [huawei-noah/Efficient-Computing#133]
Hello, thank you for your outstanding work. I would like to ask if Gold-YOLO supports  Oriented Bounding Box  detection？

**Comment by lose4578** [comment]
Our code base on the YOLOv6, so maybe you can refer this [YOLOv6-R](https://github.com/haohaolalahao/YOLOv6-R/blob/main/README-todo.md), and change the ori neck to `GD_neck`.
