### ISSUE TITLE
Could you please provide the parameters of IPG?

### ISSUE THREAD

**Issue by gitlonglong** [huawei-noah/Efficient-Computing#151]
Hello, author. Could you please provide the parameters of your SOTA model? I intend to cite IPG in my thesis. The parameter quantity of the x4 magnification I measured is much smaller than that of the x2 and x3 magnifications. Is this due to the fact that the conv_scale is set to 0?

**Comment by YuchuanTian** [comment]
Hi, Thanks for your interest in our work!

The parameters of the SOTA model are provided here: 
SRx2: https://huggingface.co/yuchuantian/IPG/blob/main/IPG_SRx2.pth
SRx3: https://huggingface.co/yuchuantian/IPG/blob/main/IPG_SRx3.pth
SRx4: https://huggingface.co/yuchuantian/IPG/blob/main/IPG_SRx4.pth

Yes, I think that is correct. While the backbones of SRx2/3/4 are almost the same, the difference lies in the usage of channel attention. IPG SRx4 does not use channel attention module, saving a large number of parameters.

**Comment by gitlonglong** [comment]
> Hi, Thanks for your interest in our work!
> 
> The parameters of the SOTA model are provided here: SRx2: https://huggingface.co/yuchuantian/IPG/blob/main/IPG_SRx2.pth SRx3: https://huggingface.co/yuchuantian/IPG/blob/main/IPG_SRx3.pth SRx4: https://huggingface.co/yuchuantian/IPG/blob/main/IPG_SRx4.pth
> 
> Yes, I think that is correct. While the backbones of SRx2/3/4 are almost the same, the difference lies in the usage of channel attention. IPG SRx4 does not use channel attention module, saving a large number of parameters.

Thank you for your reply, it solved my problem.
