### ISSUE TITLE
Your paper is very instructive. Can you provide a training model to test it? Thank you!  It would be better if there were more detailed steps to reproduce the operation. Thank you.

### ISSUE THREAD

**Issue by QQ2737499951** [huawei-noah/Efficient-Computing#2]
Your paper is very instructive. Can you provide a training model to test it? Thank you!

It would be better if there were more detailed steps to reproduce the operation. Thank you.

===========
你们的论文很有启发意义，请问能提供训练模型测试一下吗？谢谢！
如果有更详细的操作复现步骤就更好了，谢谢！

**Comment by HantingChen** [comment]
Thanks for your suggestion. The pretrained model will be uploaded.

**Comment by Ako-r** [comment]
您好，请问方便更新一下“Learning Student Networks in the Wild”论文的代码吗？

**Comment by HantingChen** [comment]
> 您好，请问方便更新一下“Learning Student Networks in the Wild”论文的代码吗？

代码正在申请开源中

**Comment by QQ2737499951** [comment]
这是来自AAAAAAAAAAAAAA
