### ISSUE TITLE
I can not find The implementation of Lerning Student Network in the wild

### ISSUE THREAD

**Issue by yan-hao-tian** [huawei-noah/Efficient-Computing#22]
The paper LSNW said that its implementation is available here.

**Comment by HantingChen** [comment]
The code is under approval and will be released in few weeks or months.

**Comment by HantingChen** [comment]
Code can be found in https://github.com/huawei-noah/Efficient-Computing/tree/master/Data-Efficient%20Model%20Compression/DFND
