### ISSUE TITLE
How to handle NAS_Bench_201 arch as tensors

### ISSUE THREAD

**Issue by AlbertiPot** [huawei-noah/Efficient-Computing#26]
Hi, many thanks for your wonderful work.

I have noticed an arch encoding method in the ReNAS which encodes an adjacent matrix with the operation and vertex flops as well as params into a 19×7×7 tensor. This works for nasbench101 but is not ok for nasbench201 since the latter views the edges as operations and nodes as the sums of the feature maps, which is just the opposite to the nasbench101: nodes as the operations. 

So the question is how to handle the nasbench201 into tensors since in the paper you have also conducted experiments on 201 dataset.

Many thanks to your cool and yyds works again!

**Comment by xiaoshingshing** [comment]
The way of representing the cell is not important. The important thing is the process of deriving the final output from the input.

I draw an example below to express the topleft cell in Figure 1 in NASBench201 paper. I hope this will help you.

![BB7F45F0-53C2-4388-96EC-5083FF3176F8](https://user-images.githubusercontent.com/22720830/145177210-033a3177-0ccc-44cc-a30a-8c1ca58b6e8e.jpg)

**Comment by AlbertiPot** [comment]
Many thanks
