### ISSUE TITLE
图像生成器（Generator）中的数据分布信息从何而来？

### ISSUE THREAD

**Issue by HELLORPG** [huawei-noah/Efficient-Computing#27]
您好，最近在拜读你们发表在CVPR 2021的文章 *Data-Free Knowledge Distillation For Image Super-Resolution*，在其中对于图像生成器的论述有一段是`where x is the training sample and p_x(x) is the distribution of the original dataset.`，但是我好像并没有在文中看到这里原始数据集的分布 p_x(x) 是从哪里获得或者计算或者设定的，也好像在你们的仓库中并没有看到对应这篇文章的源码，也可能是我学艺不精看漏了。

因此想请问一下你们，这部分的原始数据集分布p_x(x)是从哪里得到的呢？

**Comment by HantingChen** [comment]
是任意的，没有进行统计
