### ISSUE TITLE
Implementation code

### ISSUE THREAD

**Issue by Jonghoongwak** [huawei-noah/Efficient-Computing#32]
Hello, I read you paper in CVPR 2022 impressively.
Instance-Aware Dynamic Neural Network Quantization

And, I try to re-implement your framework and find your open code repository.

In this paper, the code repository was presented like below.
https://github.com/huawei-noah/Efficient-Computing : cannot find code repository. there are other papers implementation.
https://gitee.com/mindspore/models/tree/master/research/cv/DynamicQuant: does not work url address

Isn't the code prepared yet? Could you tell me your code repository of the paper?

Then, It will be very helpful.

Thanks.

**Comment by liu-zhenhua** [comment]
Thanks for the attention, the code is available with https://github.com/huawei-noah/Efficient-Computing/tree/master/Quantization/DynamicQuant.
