### ISSUE TITLE
Question about implementation of "DQNet"

### ISSUE THREAD

**Issue by junhyukso** [huawei-noah/Efficient-Computing#35]
Hello, I read you paper in CVPR 2022 .

I have a question about your implementation.

in  `resnet_quan_imagenet.py` , The `one-hot` vector, which is the number of bits selection for each layer, seems enter to the same value for all layers. 
```python
        one_hot = F.gumbel_softmax(feat, tau=1, hard=True, eps=1e-20)
        
        for m in self.layer2:
            x = m(x, one_hot)
        for m in self.layer3:
            x = m(x, one_hot)
        for m in self.layer4:
            x = m(x, one_hot)
```
In this case, aren't all the layers' bitwidth selected in the same bitwidth?

**Comment by liu-zhenhua** [comment]
Thanks for the attention. The code is the special case which all the layers selected in the same bit-width. We will update the code and you can also change the code accordingly.
