### ISSUE TITLE
[DynamicQuant] Isn't the model size about 3 times larger than the baseline?

### ISSUE THREAD

**Issue by Cheeun** [huawei-noah/Efficient-Computing#37]
Hello, 
Thanks for sharing your code.
Your paper "Instance-Aware Dynamic Neural Network Quantization" is interesting!

I have one question on the **model size** of your work.

It seems that a layer of the DynamicQuant network has to hold 3 convolution weights with different bits in order to dynamically select one for each input. (when there is 3 bit-width candidates)
This seems to **enlarge the model size by nearly 3 times** of uniform-bit quantization, although the Bit-FLOPs are maintained.
 I wonder if this impacts the **inference time**.

If I am wrong, please correct me!

**Comment by liu-zhenhua** [comment]
Thanks for the attention. Only the biggest bit-width need to be stored since we use the same Quantizer for the three bit-widths. The other bit-width can be easily obtained. During the inference, the storage of the feature map and inference time are the main bottleneck of the model.

**Comment by Cheeun** [comment]
Ah ok, I got it. Thanks for your answer!
