### ISSUE TITLE
关于DASR中的教师网络问题

### ISSUE THREAD

**Issue by Christopher0001** [huawei-noah/Efficient-Computing#40]
您好，DASR中教师网络不应该是训练好的模型吗，为什么在代码中还需要训练一遍教师网络，教师网络中的train.h5和测试集又分别是如何制作出来的呢，望回复，谢谢。

**Comment by xinghaochen** [comment]
1. 如果你已经有训练好的教师模型，则可以不用执行教师模型训练这一步骤
2. 训练数据的生成请参照：https://github.com/twtygqyy/pytorch-vdsr

**Comment by Christopher0001** [comment]
非常感谢
