### ISSUE TITLE
您好，想咨询一下AdaBin方法模型的配置问题。

### ISSUE THREAD

**Issue by zhaoxiangshun** [huawei-noah/Efficient-Computing#42]
前辈您好，我最近看您的论文感觉很棒，看了一下代码，有一点疑问，论文中在imagenet数据集下resnet18网络的结果是63.1，跑这个实验的时候self.deep_stem是设置的True还是False？

**Comment by tuzhijun** [comment]
False，采用init的缺省值

**Comment by zhaoxiangshun** [comment]
> 

好的，感谢您的回复
