### ISSUE TITLE
Where is the paper Network Expansion For Practical Training Acceleration?

### ISSUE THREAD

**Issue by qgh1223** [huawei-noah/Efficient-Computing#47]
Where is the paper Network Expansion For Practical Training Acceleration?
When will release the paper?

**Comment by dingning97** [comment]
CVPR has officially released the paper http://openaccess.thecvf.com/content/CVPR2023/papers/Ding_Network_Expansion_for_Practical_Training_Acceleration_CVPR_2023_paper.pdf
Title search via google gets to the paper as well.
