### ISSUE TITLE
关于实例感知动态量化神经网络的问题

### ISSUE THREAD

**Issue by mlscsdn** [huawei-noah/Efficient-Computing#48]
非常感谢您分享您论文的实现代码，我想问一个比较愚蠢的问题：为什么全连接层的输出刚好就是比特候选中相应比特被选择的logits呢？

**Comment by liu-zhenhua** [comment]
全连接层的输出个数是可以手动设定的，然后我们通过end-to-end训练以及Gumbel softmax保证了这点。
