### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by francis2tm** [huawei-noah/Efficient-Computing#57]
Hello,
1. Could you explain me the need for doing this? 
https://github.com/huawei-noah/Efficient-Computing/blob/5731ac7a056dfbe80d772d826e10497a1879a9e2/BinaryNetworks/AdaBin/cifar10/utils/binarylib.py#L67

2. In inference (with no training), the `gradient_approx()` works simply as a `sign()`, correct?

Thanks in advance

**Comment by tuzhijun** [comment]
1. binary the activation to {a1, a2}, you can rewrite this function in another ways, such as torch.where.

3. That's right, the gradient_approx only optimize the backward in the training stage, it works as sign() in the inference.

**Comment by francis2tm** [comment]
Thanks for the reply @tuzhijun 

1a. But why do you need to do first https://github.com/huawei-noah/Efficient-Computing/blob/master/BinaryNetworks/AdaBin/cifar10/utils/binarylib.py#L67?
1b. Why isn't https://github.com/huawei-noah/Efficient-Computing/blob/master/BinaryNetworks/AdaBin/cifar10/utils/binarylib.py#L69 sufficient?
1c. In inference only, do you only need to do https://github.com/huawei-noah/Efficient-Computing/blob/master/BinaryNetworks/AdaBin/cifar10/utils/binarylib.py#L69?

2. Thanks

**Comment by tuzhijun** [comment]
1. You are right, it should be self.alpha_a * x + self.beta_a, which is a coding mistake, thanks for pointing that out, but it doesn't affect the actual deployment process, it still can be reduced to the form a * {-1, +1} + b, just a and b need to be changed a little bit. The goal of this paper is to provide a new perspective on binary set design, you could design a better binary set based a new theory.

2. The inference process refer to the Fig.3 in the paper.
