### ISSUE TITLE
指定数据路径后，训练出错

### ISSUE THREAD

**Issue by wkx-anything** [huawei-noah/Efficient-Computing#67]
Training start...

     Epoch  iou_loss  dfl_loss  cls_loss
  0%|          | 0/21 [00:00<?, ?it/s]                                          ERROR in training steps: Default process group has not been initialized, please make sure to call init_process_group.
  0%|          | 0/21 [00:01<?, ?it/s]                                          
ERROR in training steps.
ERROR in training loop or eval/save model.

**Comment by lose4578** [comment]
Hi，can you provide more detailed error logs and your data yaml.

**Comment by 1472580twjjjjkk** [comment]
### 
![image](https://github.com/huawei-noah/Efficient-Computing/assets/117447861/64d2c0ce-4a8d-43bb-81dc-a0e696f7af2a)
![image](https://github.com/huawei-noah/Efficient-Computing/assets/117447861/94388ab3-98f6-4e99-b41e-cf367f60916c)
![image](https://github.com/huawei-noah/Efficient-Computing/assets/117447861/6f624952-c249-4181-864c-654fd7288068)

**Comment by 1472580twjjjjkk** [comment]
> e

![image](https://github.com/huawei-noah/Efficient-Computing/assets/117447861/60ecb7a3-33db-49d0-837b-48b39897425d)
This is the format of the dataset. Yolov6 format

**Comment by lose4578** [comment]
If you don't use ddp model in training (like use torch.distributed.launch), you can refer this issuse #68

**Comment by Augestern-L** [comment]
> 如果你在训练中不使用 ddp 模型（比如不使用 torch.distributed.launch），你可以参考这个 issuse #68
After I used the advice you gave, the code works fine, but it's only training with CPU, can you help me with that?

**Comment by Augestern-L** [comment]
Is it possible to then use the ddp model and make adjustments to the code

**Comment by lose4578** [comment]
The default is to use the gpu for training. If your code is running on the cpu, you may want to check the settings for --device. 
For ddp, of course, you can use ddp if you have multiple GPUs.

**Comment by Augestern-L** [comment]
> The default is to use the gpu for training. If your code is running on the cpu, you may want to check the settings for --device. For ddp, of course, you can use ddp if you have multiple GPUs.

How do I go about configuring the dataset in Gold-YOLO? Let's take coco or YOLO format datasets for example

**Comment by lose4578** [comment]
The ddp mode is not configured in config, you should to read [README](https://github.com/huawei-noah/Efficient-Computing/blob/master/Detection/Gold-YOLO/README.md), and use this commend
```
python -m torch.distributed.launch --nproc_per_node 8 tools/train.py \
									--batch 256 \
									--conf configs/gold_yolo-s.py \ # gold_yolo-m/gold_yolo-l
									--data data/coco.yaml \
									--epoch 300 \
									--fuse_ab \
									--use_syncbn \
									--device 0,1,2,3,4,5,6,7 \
									--name gold_yolo-s # gold_yolo-m/gold_yolo-l
```

For custom data sets, you can refer this [Train custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md)
