### ISSUE TITLE
Gold-YOLO配置文件对不上

### ISSUE THREAD

**Issue by imMid-Star** [huawei-noah/Efficient-Computing#71]
配置文件中的neck的某个参数是 out_channels：
neck=dict(
                type='RepGDNeck',
                num_repeats=[12, 12, 12, 12],
                out_channels=[256, 128, 128, 256, 256, 512],
                extra_cfg=dict(
                        norm_cfg=dict(type='BN', requires_grad=True),   # Here, you should change the SyncBN to BN
                        depths=2,
                        fusion_in=960,
                        ppa_in=704,
                        fusion_act=dict(type='ReLU6'),
                        fuse_block_num=3,
                        embed_dim_p=128,
                        embed_dim_n=704,
                        key_dim=8,
                        num_heads=4,
                        mlp_ratios=1,
                        attn_ratios=2,
                        c2t_stride=2,
                        drop_path_rate=0.1,
                        trans_channels=[128, 64, 128, 256],
                        pool_mode='torch'
                )
        ),
但是模型里是channels_list，维度也对不上，这里需要修改吗？
class RepGDNeck(nn.Module):
     def __init__(self, channels_list=None, num_repeats=None, block=RepVGGBlock, extra_cfg=None):
         super().__init__()

**Comment by lose4578** [comment]
You can see this line [yolo.py#L69](https://github.com/huawei-noah/Efficient-Computing/blob/master/Detection/Gold-YOLO/yolov6/models/yolo.py#L69), here the `build_network` function converts the out_channels to channels_list.
