### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

### ISSUE THREAD

**Issue by gf-zhong** [huawei-noah/Efficient-Computing#76]
I am using a single GPU and encountered an error during training，
![image](https://github.com/huawei-noah/Efficient-Computing/assets/116566889/4c87802f-712d-4fa6-afdf-d9b63b47ca72)
After searching online, it was found that there may be a problem with the Cuda version. Have you ever encountered this problem? May I ask if you can provide information on the environment version?thanks！

**Comment by gf-zhong** [comment]
When I set device=CPU, I encountered the same error as them，![image](https://github.com/huawei-noah/Efficient-Computing/assets/116566889/b8f1884d-9752-40ee-9b73-3262d03148aa)
[https://github.com/huawei-noah/Efficient-Computing/issues/68](url)
I have![image](https://github.com/huawei-noah/Efficient-Computing/assets/116566889/45470986-16ba-489d-9811-7318ae1aa760)
![image](https://github.com/huawei-noah/Efficient-Computing/assets/116566889/0a4ae595-fed4-4982-9d14-2310be03214c)

**Comment by gf-zhong** [comment]
When I initialize loss in the Trainer class of Gold YOLO yolov6 core engine. py_ Item, can already train normally, but I'm not sure if this will cause other problems![image](https://github.com/huawei-noah/Efficient-Computing/assets/116566889/acd6aeac-b6b1-476b-b3df-a6111f0d022f)

**Comment by suncheng-guihub** [comment]
Hello, self.loss_items is a float value, not list?

**Comment by lose4578** [comment]
Hi, this is my env version:
torch   1.11.0+cu113
cuda    11.3

I didn't see the same error, maybe your env had some problems.

**Comment by gf-zhong** [comment]
> 你好，这是我的环境版本： torch 1.11.0+cu113 cuda 11.3
> 
> 我没有看到同样的错误，也许你的环境有一些问题。

Yes, there may be some issues with the environment. My Pytorch version is 2.0.0 and Cuda version is 11.7. However, after the above initialization, this issue can be resolved and can be trained and tested normally.
