### ISSUE TITLE
AttributeError: 'Trainer' object has no attribute 'loss_items'

### ISSUE THREAD

**Issue by kpyon-w** [huawei-noah/Efficient-Computing#81]
![image](https://github.com/huawei-noah/Efficient-Computing/assets/99155784/fc9acff1-75d1-408e-8389-090496197e1c)
 
How to solve this problem? has no attribute "loss_items"

**Comment by lose4578** [comment]
If you don't use ddp model in training (like don't use torch.distributed.launch), you can refer this issuse https://github.com/huawei-noah/Efficient-Computing/issues/68

**Comment by thanhmvu** [comment]
I need ddp and I'm seeing this issue as well. Would appreciate any suggestions. Thanks!
