### ISSUE TITLE
coco数据集转换

### ISSUE THREAD

**Issue by 872473172** [huawei-noah/Efficient-Computing#84]
coco数据集怎么转换成yolo格式的数据集？

**Comment by lose4578** [comment]
For data convert code, you can refer this https://blog.csdn.net/djstavav/article/details/121413841.
If you want use YOLO format coco labels, you can download it directly from here [YOLO format coco labels](https://github.com/meituan/YOLOv6/releases/download/0.1.0/coco2017labels.zip)
