### ISSUE TITLE
about training

### ISSUE THREAD

**Issue by QiqLiang** [huawei-noah/Efficient-Computing#85]
你好，我有以下两个问题
1. 请问默认的gold-yolo-n的训练输入分辨率是(640,640)吗？假如我想改为长宽比不为1的输入分辨率，比如(288,512)，应该怎么修改呢？因为我看train.py里设定的img-size是一个int，默认就是矩形输入。
2. 请问如果我想利用Gold_n_dist.pt预训练权重，微调自己的数据集，但我希望能在前几十个epoch冻结backbone和neck，只训练head，再解冻，应该怎么修改代码呢？
非常感谢！！

**Comment by lose4578** [comment]
Hi
1. Maybe you can refer this tutorials: https://github.com/meituan/YOLOv6/blob/main/docs/About_training_size.md
2. We do not currently implement this feature. Maybe you can change this line [yolo.py](https://github.com/huawei-noah/Efficient-Computing/blob/master/Detection/Gold-YOLO/yolov6/models/yolo.py#L41), add code like this
```
for name, value in model.named_parameters():
    if name in need_frozen_list:
        value.requires_grad = False
```
