### ISSUE TITLE
AssertionError: Results do not correspond to current coco set

### ISSUE THREAD

**Issue by Egorundel** [huawei-noah/Efficient-Computing#86]
Hello, I have such a mistake when learning after the first epoch of learning. I teach on single GPU.

I run this command: `python3 tools/train.py --batch 4 --conf configs/gold_yolo-l.py --data data/custom.yaml --epoch 3 --fuse_ab --device 0 --name gold_yolo-l`
![Screenshot from 2023-10-17 10-23-08](https://github.com/huawei-noah/Efficient-Computing/assets/65890558/5fb08f26-8a9f-49a5-a4f0-8febf91caaa9)

Error: `AssertionError: Results do not correspond to current coco set`
![Screenshot from 2023-10-17 10-23-02](https://github.com/huawei-noah/Efficient-Computing/assets/65890558/25e710c9-6033-411d-aaea-71f6d1bef640)

My config file of Gold-Yolo-L without SyncBN:
![Screenshot from 2023-10-17 10-41-47](https://github.com/huawei-noah/Efficient-Computing/assets/65890558/2efdb0a4-2764-4e53-854f-8b7684af107e)

**Comment by lose4578** [comment]
Hi, whether you are using a custom data set. If yes, you should set the `is_coco: False` in your data/custom.yaml

**Comment by Egorundel** [comment]
@lose4578 Yes, I have a custom dataset and I already have `is_coco: False`

![2023_10_18_0gs_Kleki](https://github.com/huawei-noah/Efficient-Computing/assets/65890558/f4dcfe1f-7b86-4454-8e59-1d178ac8b934)

And I still have the error I wrote about above

**Comment by Egorundel** [comment]
@lose4578 Hi! I have this `data/custom.yaml`:
![2023_10_18_0m0_Kleki](https://github.com/huawei-noah/Efficient-Computing/assets/65890558/c69eda9e-2af0-4911-ab0e-2211eef3b8e8)

I still have the same error

**Comment by lose4578** [comment]
This looks like the code error in YOLOv6, maybe you could try to comment out `anno_path`, follow in this issuse https://github.com/meituan/YOLOv6/issues/48

**Comment by Egorundel** [comment]
@lose4578 Thank you, comrade! You are the best support!

![Screenshot from 2023-10-18 15-41-56](https://github.com/huawei-noah/Efficient-Computing/assets/65890558/fe0b1db3-b7e6-4703-b80b-0806472a06c6)
