### ISSUE TITLE
can't train with DDP commond ,about Gold-YOLO

### ISSUE THREAD

**Issue by hjg12345** [huawei-noah/Efficient-Computing#87]
I use your commond "python -m torch.distributed.launch --nproc_per_node 8 tools/train.py --device 1,2 --batch 32
", it will report I should use "torch.distributed.run", then I use "torch.distributed.run",it still can't train, the bug report information is below
.How to use DDP trainning commond?
![image](https://github.com/huawei-noah/Efficient-Computing/assets/127812522/1568ae10-a381-4a61-a84d-dba994401323)

**Comment by lose4578** [comment]
The ddp command looks fine, can you show more detailed error information.

**Comment by hjg12345** [comment]
![image](https://github.com/huawei-noah/Efficient-Computing/assets/127812522/7867c039-793e-43ab-a64b-7677fc9f5e4b)
As is shown in the figure, I train with the DDP commond,but failed; My environment is "python 3.8.16, 1.11.0+cu102”

**Comment by hjg12345** [comment]
OK,I have found the problem, thanks

**Comment by Unicorn123455678** [comment]
> 好的，我找到了问题，谢谢

你好，请问是什么问题，我也遇到了这个问题，该如何修改呢
