### ISSUE TITLE
about eval

### ISSUE THREAD

**Issue by QiqLiang** [huawei-noah/Efficient-Computing#88]
你好，我在使用你们提供的预训练模型在自己数据集上微调的时候遇到了以下问题：
保存的模型Ap值一直保持在很低的水平(0.003)且几乎没有变化，但训练损失值确实有在降低，而且对单图进行推理，其可视化结果看起来没有任何问题，请问这是为什么呢？应该如何解决？谢谢！

**Comment by lose4578** [comment]
Maybe you can check your lables in your val data.
