### ISSUE TITLE
不支持gloo

### ISSUE THREAD

**Issue by 3232731490** [huawei-noah/Efficient-Computing#90]
RuntimeError: Function argument device_ids not supported for the selected backend gloo
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 23812) of binary: E:\Conda\envs\GoldYolo\python.exe
我在自己的电脑上训练模型报这个错误，如何解决，我是Windows系统

**Comment by lose4578** [comment]
This is a ddp problem, ddp have som problem in windows. You can use dp mode to train the model.
