### ISSUE TITLE
how can i aug images more in goldyolo?

### ISSUE THREAD

**Issue by Rosal-1998** [huawei-noah/Efficient-Computing#93]
i wander how can i aug images more in goldyolo，where can i find the codes to change the sitting?
thanks you for your great work in object detection!!!!!

**Comment by lose4578** [comment]
You can find related code in model config, like here https://github.com/huawei-noah/Efficient-Computing/blob/master/Detection/Gold-YOLO/configs/gold_yolo-s.py#L76
