### ISSUE TITLE
Error Code 4: Internal Error (kOPT values for profile 0 violate shape constraints: IShuffleLayer Reshape_552: reshaping failed for tensor: 1860 reshape would change volume 24576 to 4096)

### ISSUE THREAD

**Issue by Egorundel** [huawei-noah/Efficient-Computing#99]
Hello, I have a problem and maybe it happens even at the moment of converting the weights to the ONNX model.

My command to convert to ONNX looked like this:
`python3 deploy/ONNX/export_onnx.py --weights /home/egorundel/projects/Efficient-Computing/Detection/Gold-YOLO/runs/train/gold_yolo-l1/weights/best_ckpt.pt --img-size 512 512 --dynamic-batch --end2end --with-preprocess --topk-all 100 --iou-thres 0.65 --conf-thres 0.35`

After I transferred the weights after training the model to the ONNX model, then I ran the trtexec command:
`trtexec --onnx=Efficient-Computing/Detection/Gold-YOLO/runs/train/gold_yolo-l1/weights/best_ckpt.onnx --saveEngine=yolo_gold.trt --minShapes=images:1x3x512x512 --optShapes=images:6x3x512x512 --maxShapes=images:12x3x512x512 --useCudaGraph --memPoolSize=workspace:3000 --noTF32 --fp16`

I have an error when converting ONNX model to TensorRT Engine:
`Error[4]: kOPT values for profile 0 violate shape constraints: IShuffleLayer Reshape_552: reshaping failed for tensor: 1860 reshape would change volume 24576 to 4096`

`Error[4]: [shapeCompiler.cpp::evaluateShapeChecks::1276] Error Code 4: Internal Error (kOPT values for profile 0 violate shape constraints: IShuffleLayer Reshape_552: reshaping failed for tensor: 1860 reshape would change volume 24576 to 4096)`

![Screenshot from 2023-10-24 11-12-11](https://github.com/huawei-noah/Efficient-Computing/assets/65890558/f708dd65-b8c5-4749-affd-736a51baa51e)

In Netron.App I found the node Reshape_552, but I didn't understand what was wrong.
![Screenshot from 2023-10-24 11-52-18](https://github.com/huawei-noah/Efficient-Computing/assets/65890558/ebdce2c5-de8b-4aa2-9087-002881d3d444)

What could be the problem?

**Comment by lose4578** [comment]
Sorry, we haven't seen anything like this, Maybe you can refer this https://github.com/open-mmlab/mmdeploy/issues/44.

**Comment by Egorundel** [comment]
@lose4578 

Unfortunately, I have not found a solution to my problem. It seems to me that in the neural network codes, you need to change the Reshape function so that it is created with dynamic forms, as it is done in the issue that you recommended:
```
_base_ = ['./segmentation_static.py', '../_base_/backends/tensorrt.py']

onnx_config = dict(input_shape=[1024, 512])
backend_config = dict(
    common_config=dict(max_workspace_size=1 << 30),
    model_inputs=[
        dict(
            input_shapes=dict(
                input=dict(
                    min_shape=[6, 3, 512, 1024],
                    opt_shape=[6, 3, 512, 1024],
                    max_shape=[6, 3, 512, 1024])))
    ])
```

But I didn't find where exactly it needs to be inserted in your code :(

**Comment by Egorundel** [comment]
The problem was solved using `onnx graphsurgeon`:

https://github.com/NVIDIA/TensorRT/tree/release/8.6/tools/onnx-graphsurgeon/examples/10_dynamic_batch_size

With this tool you can make a dynamic batch size in all nodes
![2023_10_31_0go_Kleki](https://github.com/huawei-noah/Efficient-Computing/assets/65890558/e34c6e66-454f-40ed-91b5-b94e35016437)
